### ISSUE TITLE
BUG - List of Categories for which description is not pulled in Kibana

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#627]
1. Interest Accrued
2. Meals & Entertainment
3. Bank Charges & Fees
4. Advertising & Marketing
5. Admin Expenses
6. Sales of Product Income

**Comment by nutank** [comment]
Related tickets:
- [ ] BUG - Descriptions not being pulled in Kibana for Category Salaries and Wages #624
- [ ] BUG - Descriptions not being pulled in Kibana for Category Rent & Lease #626
- [ ] BUG - Category " Travel ", qbparentid= 353: Description is not displayed on the table in the toppeq website #620

**Comment by robiulpro** [comment]
Description added to table.

**Comment by HazelColaco19** [comment]
Description cannot be viewed on the table for all categories

![image](https://user-images.githubusercontent.com/55691499/81566218-332bde80-93b8-11ea-975e-28695b71a8c2.png)

**Comment by HazelColaco19** [comment]
Fixed for all categories mentioned above. Checked between range 1 Jan 2020 - 11 May 2020

![image](https://user-images.githubusercontent.com/55691499/81566745-f01e3b00-93b8-11ea-8900-c74bfee1144e.png)
