### ISSUE TITLE
BUG - Opening Balance not matching for the following Categories. leads to final balance mismatch

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#629]
Date Range: 1 feb 2020 -  8 may 2020

List of Categories:

- [x] 1. Interest Accrued
- [x] 2. Bank Charges & Fees
- [x] 3. Advertising & Marketing
- [x] 4. Admin Expenses
- [ ] 5. Sales of Product Income

**Comment by nutank** [comment]
Related tickets:
- [ ] BUG - Opening Balance not matching for Rent & Lease #625
- [ ] BUG - Salaries and wages : Opening balance mismatch. Range: 1 feb - 8 may, 2020 #623
- [ ] BUG - Opening Balance of Category " telephone Charges " mismatches from QB entry #622

**Comment by legred21** [comment]
@HazelColaco19 Just confirm if Opening balance and beginning balance is the same or not. As per quickbook general ledger and quickbook data table it looks different

**Comment by HazelColaco19** [comment]
@legred21  Yes it is the same. However I tested it differently this time where in I chose Flipmo company = 32. The Opening Cash Balance from Feb 1 - may 8 2020 does not match with Closing Cash Balance from Jan 1, 2019 - jan 31, 2020 for the following category:

- [ ] Sales of Product Income

![image](https://user-images.githubusercontent.com/55691499/82647034-308c7d00-9c33-11ea-8831-39e1622b35d8.png)

![image](https://user-images.githubusercontent.com/55691499/82647084-45691080-9c33-11ea-8cfe-97eef1ea198f.png)
